### ISSUE TITLE
CasProcessor.sln: configuration 指定の誤り

### ISSUE THREAD

**Issue by srx6** [dtvgit/CasProcessor#1]
GlobalSection(ProjectConfigurationPlatforms) ですが、
  {6A0D1EF7-A400-4351-9C26-E7CB46B0B554}.Release|x64.ActiveCfg = Debug|x64
  {6A0D1EF7-A400-4351-9C26-E7CB46B0B554}.Release|x64.Build.0 = Debug|x64
の2カ所、それぞれの行末は Debug|x64 ではなく Release|x64 ですね。

**Comment by dtvgit** [comment]
ご指摘感謝いたします。リクエストをマージ致しました
